### ISSUE TITLE
[Feature]: 可視化スクリプトを公開する

### ISSUE THREAD

**Issue by Okabe-Junya** [tsukuba-websci/MPS-TOM-Urnmodel#25]
### Feature description

可視化スクリプトを公開する．

full-search, QD, GA の結果を比較，可視化できるようなスクリプトを公開する．

### Motivation

結果を論文に載せねば...なので

### Additional context

いくつか検討事項がありそう．

1. 可視化スクリプトはどこに配置するのか
    a. ルートに `visualize` などとしておくのか，`/lib` に配置するのか...
    b. どうやって実行するのか，結果をどこに吐くのか，結果をgit管理対象にするのか... 
2. （qdやgaの）実行結果の出力形式が変更されているので，既存のスクリプトをこれらの変更に対応させる必要がありそう．
    a. 変更の内容は https://github.com/tsukuba-websci/MPS-TOM-Urnmodel/issues/6#issue-1746327557 に書いてある

**Comment by Okabe-Junya** [comment]
@krmr73 

可視化周りの話ってどんな感じですか？？ && これ任せてもいいですか？？

**Comment by krmr73** [comment]
出力形式の変更が終わってから私がやります！

> 1. 可視化スクリプトはどこに配置するのか
a. ルートに visualize などとしておくのか，/lib に配置するのか...
b. どうやって実行するのか，結果をどこに吐くのか，結果をgit管理対象にするのか...

これに関してはルートに `visualize`などとしておき、他と同じように`/results`に結果を吐くようにしようと考えています。
今まではQDの結果から壺モデルを走らせる部分と画像を出力する部分が同じスクリプトになっていたので、それを分けて画像ファイルを出力する部分はgit管理外、壺モデルを走らせた結果はgit管理下におこうと思っています。

**Comment by krmr73** [comment]
可視化する図とそのために必要な情報
## GA,QD探索時のタイムライン
全個体の距離の平均と標準偏差 (実線)
最適な個体の距離 (点線)
### 必要な情報
- `<ga,qd>/results/<target>/archives/00000???.csv`

## レーダーチャート
ターゲットデータ,fullsearch,GA,QDの10個の指標を示す
fullsearch,GA,QDは10回壺モデルを走らせた時の平均の値を用いる
### 必要な情報
- `data/<target>.csv`
- `full-search/results/full_search.csv`
- ga, qdで求めた最適なrho,nu,r,fの組みで10回モデルを走らせた時の10個の指標のデータ（未）
  - `<ga,qd>/results/<target>/best.csv`の値から↑を求める必要がある

## 棒グラフ
fullsearch,GA,QDのターゲットデータに対する距離の平均と標準偏差を示す
レーダーチャートと同様に10回壺モデルを走らせた時の平均と分散の値を用いる
### 必要な情報
- `data/<target>.csv`
- `full-search/results/full_search.csv`
- ga, qdで求めた最適なrho,nu,r,fの組みで10回モデルを走らせた時の10個の指標のデータ（未）
  - `<ga,qd>/results/<target>/best.csv`の値から↑を求める必要がある
  
## 遺伝子の表
QD (GAも？)の実データに対して距離が小さいものベスト5のrho,nu,r,fを示す
視覚的にわかりやすいように、値の大きさに対応するように色をつける
### 必要な情報
-  `<ga,qd>/results/<target>/archives/00000499.csv`
