### ISSUE TITLE
[Feature]: 出力形式の細々とした変更

### ISSUE THREAD

**Issue by krmr73** [tsukuba-websci/MPS-TOM-Urnmodel#37]
### Feature description

1. QDとGAで出力するobjective からdistanceに変更し、絶対値を取った値にする
2. GAの`best.csv`の出力に個体数、交叉率、突然変異率の情報を追加する
3. QDの`best.csv`の出力にエリート個体の数（=占有しているセルの数）情報を追加する（できれば）

### Motivation

1. QDとGAでobjectiveの表記揺れがある（符号が異なっている）
 - objectiveは値が大きいほど良いようにしたいので、-がついた形
 - distanceは値が小さいほど良いので、絶対値を取った形
 が正しいが、どちらにしろ可視化時点で絶対値を取る必要があるので、distanceに統一することにする
2. 後から何のパラメータで実験したか分からなくなりそうなので、追加する
3. 論文にエリート個体の数（=占有しているセルの数）の情報は記述することになるため、簡単に確認できると嬉しい。`archive.pkl`から確認することもできるので、できればやりたいというタスクにする

**Comment by Okabe-Junya** [comment]
> GAのbest.csvの出力に個体数、交叉率、突然変異率の情報を追加する

は，以下の関数の引数に，個体数、交叉率、突然変異率の情報を入れてあげれば対応できそう

https://github.com/tsukuba-websci/MPS-TOM-Urnmodel/blob/ca129df15ca6e398f2227cf3433632ecd6213fa7/ga/io_utils.py#L36-L50
