### ISSUE TITLE
[Bug]: GAの実行によって出力されるrho, nuに負の値が含まれる

### ISSUE THREAD

**Issue by krmr73** [tsukuba-websci/MPS-TOM-Urnmodel#46]
### Bug description

確率的に高くはないが、rho,nuの値が負のものが出力されている。
突然変異によって作られる遺伝子のrho,nuの値域がrecentness, frequencyの値域と同じになってしまっているところが原因ではないかと思われる。
https://github.com/tsukuba-websci/MPS-TOM-Urnmodel/blob/4d825b15f6ae291978dffbb3022b3d165577d5ec/ga/ga.py#LL107C1-L121C1

### How to reproduce

任意のデータセットで下記のコマンドを実行する。
```
$ pwd # => /path/to/ga
$ python main.py <population_size> <mutation_rate> <cross_rate> <target_dataset>
```
`results/<target_dataset>/archives`のcsvファイルをいくつか確認する。（負の値が出力される確率は高くはないので、全部正の値になっている場合もある）

### Expected behavior

rho,nuの値域は0~30なので、その範囲の値のみに限られる。

### Actual behavior

大多数は0~30の値だが、稀に-1~0の値が混じっている。

### Additional context

@Okabe-Junya 確認お願いします！

**Comment by Okabe-Junya** [comment]
これは、コンストラクタの中で min_val, max_val が、-1, 1になっているのが原因ぽそうです。

旧repoでもそうだったと認識していたのですが、違いましたっけ…??いずれにしてもバグフィックスはここをいじれば良さそうです

**Comment by Okabe-Junya** [comment]
あ、ごめんなさい、勘違いしていました。↑で説明してくれた通りです。（突然変異の値域が分かれていないことが由来）

いじる場所はmin_val, max_valであっています。
