### ISSUE TITLE
[Feature]: 棒グラフに有意差を示す表示を追加する

### ISSUE THREAD

**Issue by krmr73** [tsukuba-websci/MPS-TOM-Urnmodel#51]
### Feature description

統計的な優位差の表示を実データ・合成データの棒グラフに追加する。こんなイメージ↓
![image](https://github.com/tsukuba-websci/MPS-TOM-Urnmodel/assets/88866882/9702aa14-b76c-41a1-9f1d-1208df0f4df7)

https://qiita.com/tokudo/items/7c2dd1688e31abe6789d

### Additional context

前回は有意差検定に関して完全に @Okabe-Junya くんに任せていてよく分かっていないので確認する。

**Comment by Okabe-Junya** [comment]
$p = 0.05, 0.01$ でやっておく

**Comment by krmr73** [comment]
棒グラフを論文から省くことになったため、このissueは閉じる
