### ISSUE TITLE
[Feature]: GAの出力形式の変更

### ISSUE THREAD

**Issue by Okabe-Junya** [tsukuba-websci/MPS-TOM-Urnmodel#6]
### Feature description

可視化スクリプトを効率的に使えるように，GAの結果の出力形式や，アーカイブの出力形式を修正する．

### Motivation

GAとQDでは，依存するライブラリの差などにより，アーカイブデータや出力結果が異なる形式になってしまっていた．

このような背景ゆえ，2つの実験の結果を可視化したいときなど，大変になることがあった．

1. 修正する十分な時間が確保できたこと
2. このリポジトリは今後も使われること

の経緯から，このタイミングで修正を行う．

### Additional context

~~結果を出力するディレクトリの構成はは以下のようにする．~~

```text
<target_data>
	- 001/
 		- archives
   			- 00000000.csv
   			- ...
 		- conclusion.csv
	- 002/
		- archives
   			- 00000000.csv
			- 00000123.csv
   			- ...
 		- conclusion.csv
	- ...
```

特に `XXX/archives` 以下の各csvは以下のようなスキーマにする．

```csv
rho,nu,recentness,frequency,objective
（個体の数だけデータが保存される）
```

また，`conclusion.csv` は以下のような形式にする．

```
rho,nu,recentness,frequency,gamma,c,oc,oo,nc,no,y,r,h,g
(最良の個体に対応する1行分の情報を出力する)
```

**Comment by Okabe-Junya** [comment]
GAではロギングもしやすいように，`/ga/log` 以下にログ出力もはくようにする

**Comment by krmr73** [comment]
@Okabe-Junya 
`conclusion.csv`の形式少し訂正します。項目としては世代ごとのものと同じでお願いします！
```
rho,nu,recentness,frequency,objective
(最良の個体に対応する1行分の情報を出力する)
```

**Comment by krmr73** [comment]
あと細かいところですが論文の方の表記がfriendshipでなくfrequencyなので、コードもそちらに統一したいと思ってます

**Comment by krmr73** [comment]
変更が多くて申し訳ないですが、連番のディレクトリで保存するのはなしにして下記の形式にしてもいいですか？
QDの方で連番にするのが少し大変そうなのと、可視化のときにどの結果を採用するかという問題もありそうと思ったので。
```
<target_data>
        - archives
                - 00000000.csv
                - ...
        - best.csv
```

**Comment by Okabe-Junya** [comment]
https://github.com/tsukuba-websci/MPS-TOM-Urnmodel/issues/6#issuecomment-1585980360, https://github.com/tsukuba-websci/MPS-TOM-Urnmodel/issues/6#issuecomment-1585999573 はそのまま対応しておきます．



> 変更が多くて申し訳ないですが、連番のディレクトリで保存するのはなしにして下記の形式にしてもいいですか？ QDの方で連番にするのが少し大変そうなのと、可視化のときにどの結果を採用するかという問題もありそうと思ったので。
> 
> ```
> <target_data>
>         - archives
>                 - 00000000.csv
>                 - ...
>         - best.csv
> ```

は別でPR立てて対応することにします．これって

1. `-f` `--force` のような引数をつけたときのみ結果を強制的に上書きする
    a. `--force` をつけていない && 結果がすでに存在している 場合は何もしない 
2. デフォルトで既存の結果に上書きする

のどっちの方がいいですか？？

**Comment by krmr73** [comment]
ありがとうございます。お願いします。

マストではないですが、1の方が嬉しいです。

**Comment by Okabe-Junya** [comment]
1で対応しておきます🙆‍♂️

**Comment by Okabe-Junya** [comment]
> あと細かいところですが論文の方の表記がfriendshipでなくfrequencyなので、コードもそちらに統一したいと思ってます

https://github.com/tsukuba-websci/MPS-TOM-Urnmodel/blob/475f54e08df9d5b24a4aa2226c617234d8232c83/lib/history2vec.py#L10

ここで表記ゆれが発生しているので，QDの方と合わせて修正をお願いします．（GAの方は修正済みで，`/ga` 内のParamsに当てています）
